[project]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ff"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

build = """
git checkout -- src/ff/ffinit.f && \
sed -i "s|/user/gj/lib/|$CONDA_PREFIX/share/ff/|g" src/ff/ffinit.f && \
sed -i "s|/usr/local/ff/|$CONDA_PREFIX/share/ff/|g" src/ff/ffinit.f && \
cd src/ff && \
make clean && \
export CPU_COUNT=10 && \
make --jobs=$CPU_COUNT FC=$FC FFLAGS="$FFLAGS -std=legacy -ffixed-line-length-none" DEST=$CONDA_PREFIX/lib
"""

install = { cmd = """
cd src/ff && \
make clean && \
export CPU_COUNT=10 && \
make FC=$FC FFLAGS="$FFLAGS -std=legacy -ffixed-line-length-none" DEST=$CONDA_PREFIX/lib install && \
echo $? && \
mkdir -p $CONDA_PREFIX/share/ff/ && \
cp fferr.dat $CONDA_PREFIX/share/ff/ && \
cp ffwarn.dat $CONDA_PREFIX/share/ff/ && \
make clean
""", depends-on = ["build"] }

test = """
cd src/ff && \
make clean && \
make npointes FC=$FC FFLAGS="$FFLAGS -std=legacy -ffixed-line-length-none" DEST=$CONDA_PREFIX/lib && \
./npointes
"""

clean = """
git checkout -- src/ff/ffinit.f && \
git checkout -- src/ff/Makefile && \
cd src/ff && \
make clean
"""

start = { depends-on = ["install", "test", "clean"] }

[dependencies]
cxx-compiler = ">=1.8.0,<2"
fortran-compiler = ">=1.8.0,<2"
make = ">=4.4.1,<5"
sed = ">=4.8,<5"
