[project]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ff"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

build = """
cd src/ff && \
make clean && \
make DEST=$CONDA_PREFIX/lib
"""

install = { cmd = "cd src/ff && make DEST=$CONDA_PREFIX/lib install && make clean", depends-on = ["build"] }

start = { depends-on = ["install"] }

[dependencies]
cxx-compiler = ">=1.8.0,<2"
fortran-compiler = ">=1.8.0,<2"
make = ">=4.4.1,<5"
